services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=movie_play_db'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
        - pgdata:/data/postgres
volumes:
      pgdata: